focus_borders:
  active:
    enabled: false
    color: "#2853ff"
  inactive:
    enabled: false

gaps:
  inner_gap: 10
  outer_gap: 3

general:
  show_floating_on_top: false
  toggle_workspace_on_refocus: true
  window_animations: "false"
  focus_follows_cursor: false
  cursor_follows_focus: true

bar:
  opacity: 1
  offset_x: 0
  offset_y: 0
  font_family: "JetBrainsMono Nerd Font"
  height: 20
  border_radius: 0
  position: "top"
  background: "#000000" # or transparent
  foreground: "#f2e9de" # or transparent
  font_size: "14px"
  border_width: 0
  vertical: "v"
  horizontal: "b"
  components_left:
    - type: "cpu"
      font_size: 13
      label: "<attr fs = '13.5' fg='#2853ff'>   </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 1000

    - type: "gpu"
      font_size: 13
      label: "<attr fs='17' fg='#2853ff'>󱝊  </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 1000

    - type: "memory"
      label: "<attr fs='14' fg='#2853ff'>   </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 100

    - type: "music"
      font_size: 13
      label_not_playing: "<attr fg='#2853ff'>󰝛 </attr>"
      label_paused: "<attr fg='#ef596f'> ▶</attr> {song_title} - {artist_name} "
      label_playing: "<attr fg='#2853ff'> 󰝚 </attr> {song_title} - {artist_name} "
      max_title_length: 35
      max_artist_length: 20

    # - type: "text"
    #   text: ""

    # - type: "system tray"
    #   padding: "3px 0px"
    #   foreground: "#2853ff"

  components_center:
    - type: "workspaces"
      font_size: 15
      border_width: 1
      border_color: "#2853ff"
      border_radius: 2
      focused_workspace_background: "#21262d"
      focused_workspace_foreground: "#2853ff"
      displayed_workspace_background: "#21262d"
      default_workspace_background: "transparent"
      margin: "0px 10px 0px 0px"

  components_right:
    - type: "tiling direction"
      font_size: 13
      label_horizontal: ""
      label_vertical: ""
      foreground: "#2853ff"
      padding: "0 10px"

    - type: "network"
      font_size: 13
      refresh_interval_ms: 50
      foreground: "#2853ff"
      padding: "0 5px"
      font_family: "JetBrainsMono Nerd Font"
      label_no_internet: "<attr fg='#ef596f'></attr> "
      label_ethernet: "󰈁"
      label_wifi_strength_0: "<attr fg='#ef596f'>󰤯   </attr> "
      label_wifi_strength_25: "<attr fg='#e5c07b'󰤟   </attr> "
      label_wifi_strength_50: "<attr fg='#e5c07b'>󰤢   </attr> "
      label_wifi_strength_75: "<attr fg='#89ca78'>󰤥   </attr> "
      label_wifi_strength_100: "<attr fg='#89ca78'>󰤨   </attr> "

      # new blue: #2853ff
      # old blue: #0078d4
    - type: "volume"
      font_size: 13
      label: "<attr fs='15' fg='#2853ff'> </attr>{volume_level}%"
      padding: "0 5px"
      label_mute: "<attr fs='15' fg='#ef596f'>󰸈  </attr>{volume_level}%"
      label_low: "<attr fs='15' fg='#2853ff'>  </attr>{volume_level}%"
      label_medium: "<attr fs='15' fg='#2853ff'>󰕾  </attr>{volume_level}%"
      label_high: "<attr fs='15' fg='#2853ff'>   </attr>{volume_level}%"

    - type: "battery"
      padding: "0 5px"
      font_size: 13

      label_draining: "<attr fs='14' fg='#2853ff'>󰁹</attr> {battery_level}%"
      label_power_saver: "<attr fs='14' fg='#ef596f'>󱉞 </attr> {battery_level}%"
      label_charging: "<attr fs='14' fg='#89ca78'>󰂄</attr> {battery_level}%"

    - type: "clock"
      font_size: 13
      foreground: "#f2e9de"
      time_formatting: "ddd MMM d, hh:mm tt"
      padding: "0 5px"
      margin: "0 0 0 5px"

    # - type: "window title"
    #   font_size: 11
    #   padding: "0px 0px 0px 150px"

workspaces:
  # display_name: " "
  - name: "term"
    keep_alive: false
    display_name: "  " # Terminal

  - name: "1"
    display_name: "  " # Personal house house icon
    keep_alive: false

  - name: "2"
    display_name: "  " # Tabb
    keep_alive: false

  - name: "3"
    display_name: " " # Governor's School
    keep_alive: false

  - name: "4"
    display_name: "󰑴  " # College
    keep_alive: false

  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

  - name: "ticktick"
    display_name: " "
    keep_alive: true

  - name: "spotify"
    display_name: "  "
    keep_alive: false

window_rules:
  # Window resizes
  - command: "resize borders -2px -7px -15px -7px"
    match_process_name: "sioyek"
  - command: "resize borders +1px -7px -7px -8px"
    match_process_name: "neovide"
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam|vivaldi"
  - command: "resize borders -0px -9px -9px -9px"
    match_process_name: "TickTick"
  - command: "resize borders 0px 0px +3px +3px"
    match_process_name: "thorium"
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "alacritty"

  # Auto tile or float
  - command: "set tiling"
    match_process_name: "sioyek"
  - command: "set floating"
    match_title: "Go to"
  - command: "set floating"
    match_title: "Settings"
  - command: "set floating"
    match_class_name: "#32770|SunAwtDialog"
  - command: "set floating"
    match_process_name: "Taskmgr"
  - command: "set floating"
    match_title: "This PC|Picture in picture|Spotify"
  - command: "set floating"
    match_process_name: "This PC"
  - command: "set floating"
    match_process_name: "localsend_app"
  - command: "set floating"
    match_process_name: "PowerToys.Peek.UI"
  - command: "set floating"
    match_class_name: "open"
  - command: "set floating"
    match_process_name: "Screen Snipping"
  - command: "set floating"
    match_class_name: "ApplicationFrameWindow|HwndWrapper*"
  - command: "set floating"
    match_process_name: "TickTick"
  - command: "set floating"
    match_title: "Sync to Most Recent Page Read" # Kindle
  - command: "set floating"
    match_process_name: "explorer|ApplicationFrameHost"
    match_title: "Control Panel|Settings"
  - command: "set floating"
    match_title: "Downloads"

  # Ignore
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
  - command: "ignore"
    match_process_name: "/Taskmngr|ScreenClippingHost/"
  - command: "ignore"
    match_process_name: "Flow.Launcher"
  - command: "ignore"
    match_title: "WinUI Desktop" # PowerToys Peek
  - command: "ignore"
    match_title: "Run"
  - command: "ignore"
    match_title: "Focus Timer" # TickTick
  - command: "ignore"
    match_process_name: "msrdc" # WSL gui windows
  - command: "ignore"
    match_process_name: "EXCEL"

  # Auto send to workspace
  - command: "move to workspace term"
    match_process_name: "alacritty"
  - command: "move to workspace spotify"
    match_process_name: "Spotify"
  - command: "move to workspace ticktick"
    match_process_name: "brave"
    match_title: "/TickTick/"

keybindings:
  # Focus windows
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Window movement
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Window resize
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # General actions
  - command: "tiling direction toggle"
    binding: "Alt+Shift+D"
  - command: "toggle focus mode"
    binding: "Alt+F"
  - command: "toggle floating"
    binding: "Alt+Shift+F"
  - command: "toggle maximized"
    binding: "Alt+X"
  - command: "set minimized"
    bindings: ["Alt+M", "Alt+C"]
  - command: "close"
    binding: "Alt+Q"
  - command: "exit wm"
    binding: "Alt+Shift+Z"
  - command: "reload config"
    binding: "Alt+Shift+R"
  # - command: "tiling direction vertical"
  #   binding: "Alt+V"

  # Open programs
  - command: "exec alacritty"
    binding: "Alt+Enter"
  - command: "exec alacritty -o \"shell='pwsh'\"" #alacritty in windows
    binding: "Alt+Shift+Enter"
  - command: 'exec floorp'
    binding: "Alt+W"

  # Focus specific workspaces
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"
  - command: "focus workspace ticktick"
    binding: "Alt+E"
  - command: "focus workspace term"
    binding: "Alt+Escape"
  - command: "focus workspace spotify"
    binding: "Alt+S"

  # Focus relative workspaces
  - command: "focus workspace recent"
    binding: "Alt+R"
  - command: "focus workspace next"
    binding: "Alt+D"
  - command: "focus workspace prev"
    binding: "Alt+A"

  # Move to workspace
  - commands: ["move to workspace term"]
    binding: "Alt+Shift+Escape"
  - commands: ["move to workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9"]
    binding: "Alt+Shift+9"
  - commands: ["move to workspace ticktick"]
    binding: "Alt+Shift+E"
  - commands: ["move to workspace spotify"]
    binding: "Alt+Shift+S"
