focus_borders:
  active:
    enabled: true
    color: "#0078d4"
  inactive:
    enabled: false

gaps:
  inner_gap: 10
  outer_gap: 10

general:
  show_floating_on_top: false
  toggle_workspace_on_refocus: true
  window_animations: "unchanged"
  focus_follows_cursor: false
  cursor_follows_focus: false

bar:
  opacity: 1
  offset_x: 0
  offset_y: 0
  font_family: "JetBrainsMono Nerd Font"
  height: 22
  border_radius: 0
  position: "top"
  background: "#000000" # or transparent
  foreground: "#f0f6fc" # or transparent
  font_size: "13px"
  border_width: 0
  vertical: "v"
  horizontal: "b"
  components_left:
    # - type: "text"
    #   text: ""
    - type: "cpu"
      label: "<attr fs = '13.5' fg='#0078d4'>   </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 1000
    - type: "gpu"
      label: "<attr fs='17' fg='#0078d4'>󱝊  </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 1000
    - type: "memory"
      label: "<attr fs='14' fg='#0078d4'>   </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 100
    # - type: "system tray"
    #   padding: "3px 0px"
    #   foreground: "#0078d4"
    - type: "music"
      label_not_playing: "󰝛 "
      label_paused: "<attr fg='#0078d4'> ▶</attr> {song_title} - {artist_name} "
      label_playing: "<attr fg='#0078d4'>  󰝚 </attr> {song_title} - {artist_name} "
      max_title_length: 35
      max_artist_length: 20
  components_center:
    - type: "workspaces"
      border_width: 1
      border_color: "#0078d4"
      border_radius: 2
      focused_workspace_background: "#21262d"
      focused_workspace_foreground: "#0078d4"
      displayed_workspace_background: "#21262d"
      default_workspace_background: "transparent"
      margin: "0px 10px 0px 0px"
  components_right:
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      foreground: "#0078d4"
      padding: "0 5px"

    - type: "network"
      foreground: "#0078d4"
      padding: "0 7px"
      font_family: "JetBrainsMono Nerd Font Mono"
      label_no_internet: ""
      label_ethernet: "󰈁"
      label_wifi_strength_0: "󰤯"
      label_wifi_strength_25: "󰤟"
      label_wifi_strength_50: "󰤢"
      label_wifi_strength_75: "󰤥"
      label_wifi_strength_100: "󰤨"

    - type: "volume"
      label: "<attr fs='15' fg='#0078d4'>  </attr>{volume_level}%"
      padding: "0 5px"
      label_low: "<attr fs='15' fg='#0078d4'>  </attr>{volume_level}%"
      label_medium: "<attr fs='15' fg='#0078d4'>󰕾  </attr>{volume_level}%"
      label_high: "<attr fs='15' fg='#0078d4'>  </attr>{volume_level}%"
      label_mute: "<attr fs='15' fg='#0078d4'>󰸈  </attr>{volume_level}%"

    - type: "battery"
      padding: "0 5px"
      label_draining: "<attr fs='14' fg='#0078d4'>󰁹 </attr> {battery_level}%"
      label_power_saver: "<attr fs='14' fg='#e5c07b'>󱉞 </attr> {battery_level}%"
      label_charging: "<attr fs='14' fg='#89ca78'>󰂄 </attr> {battery_level}%"

    - type: "clock"
      foreground: "#ffffff"
      time_formatting: "ddd MMM d, hh:mm tt"
      padding: "0 5px"
      margin: "0 0 0 5px"

workspaces:
  - name: "terminal"
    display_name: " "
  - name: ">"
    display_name: "Personal"
  - name: "2"
    display_name: "Tabb"
  - name: "3"
    display_name: "GSST"
  - name: "4"
    display_name: "College"
  - name: "5"
    display_name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
  - name: "ticktick"
    display_name: " "

window_rules:
  - command: "move to workspace terminal"
    match_process_name: "alacritty"

  - command: "resize borders -2px -7px -15px -7px"
    match_process_name: "sioyek"

  - command: "resize borders +1px -7px -7px -8px"
    match_process_name: "neovide"

  - command: "set floating"
    match_class_name: "#32770|SunAwtDialog"

  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam|vivaldi"

  - command: "resize borders -0px -9px -9px -9px"
    match_process_name: "TickTick"

  - command: "resize borders 0px 0px +3px +3px"
    match_process_name: "thorium"

  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "alacritty"

  - command: "set floating"
    match_process_name: "Taskmgr"

  - command: "set floating"
    match_title: "This PC|Picture in picture|Spotify"

  - command: "set floating"
    match_process_name: "This PC"

  - command: "set floating"
    match_process_name: "localsend_app"

  - command: "set floating"
    match_process_name: "PowerToys.Peek.UI"

  - command: "set floating"
    match_class_name: "open"

  - command: "set floating"
    match_process_name: "Screen Snipping"

  - command: "ignore"
    match_process_name: "/Taskmngr|ScreenClippingHost/"

  - command: "ignore"
    match_process_name: "Flow.Launcher"

  - command: "set floating"
    match_class_name: "ApplicationFrameWindow|HwndWrapper*"

  - command: "set floating"
    match_process_name: "TickTick"

  - command: "set floating"
    match_title: "Sync to Most Recent Page Read" # Kindle

  - command: "set floating"
    match_process_name: "explorer|ApplicationFrameHost"
    match_title: "Control Panel|Settings"

  - command: "ignore"
    match_title: "WinUI Desktop" # PowerToys Peek

  - command: "ignore"
    match_title: "Run"

  - command: "ignore"
    match_title: "Focus Timer" # TickTick

  - command: "ignore"
    match_process_name: "msrdc" # WSL gui windows

  - command: "set floating"
    match_title: "Downloads"

  - command: "ignore"
    match_process_name: "EXCEL"

  - command: "set floating"
    match_title: "Go to"

  - command: "set floating"
    match_title: "Settings"


keybindings:
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]

  - command: "focus up"
    bindings: ["Control+Alt+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["Control+Alt+J", "Alt+Down"]

  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  - command: "move to workspace terminal"
    binding: "Alt+Shift+Escape"

  - command: "focus workspace recent"
    binding: "Alt+R"

  # - command: "tiling direction vertical"
  #   binding: "Alt+V"

  - command: "tiling direction toggle"
    binding: "Alt+Shift+D"

  - command: "toggle focus mode"
    binding: "Alt+F"

  - command: "toggle floating"
    binding: "Alt+Shift+F"

  - command: "toggle maximized"
    binding: "Alt+X"

  - command: "set minimized"
    bindings: ["Alt+M", "Alt+C"]

  - command: "close"
    binding: "Alt+Q"

  - command: "exit wm"
    binding: "Alt+Shift+Z"

  - command: "reload config"
    binding: "Alt+Shift+R"

  - command: "exec alacritty"
    binding: "Alt+Enter"

  - command: "exec alacritty -o \"shell='pwsh'\"" # alacritty in windows
    binding: "Alt+Shift+Enter"

  - command: 'exec floorp'
    binding: "Alt+W"

  - command: "focus workspace >"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"
  - command: "focus workspace ticktick"
    binding: "Alt+E"
  - command: "focus workspace terminal"
    binding: "Alt+Escape"

  - commands: ["move to workspace >"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9"]
    binding: "Alt+Shift+9"
  - commands: ["move to workspace ticktick"]
    binding: "Alt+Shift+0"
