white: &WHITE "#fefefe"
black: &BLACK "#000000"
yellow: &YELLOW "#e5c07b"
green: &GREEN "#89ca78"
red: &RED "#e06c75"
color_main: &COLOR_MAIN "#2288DC"
semi_transparent: &SEMI_TRANSPARENT "#1313135E"

focus_borders:
  active:
    enabled: false
    color: *WHITE
  inactive:
    enabled: true
    color: *BLACK

gaps:
  inner_gap: 0
  outer_gap: 1

general:
  show_floating_on_top: false
  toggle_workspace_on_refocus: true
  window_animations: "false" # or "unchanged"
  focus_follows_cursor: false
  cursor_follows_focus: false
  center_new_floating_windows: true
  floating_window_move_amount: "3%"

bar:
  opacity: 1
  offset_x: 0
  offset_y: 0
  font_family: "JetBrainsMono Nerd Font"
  height: 20
  border_radius: 0
  position: "top"
  background: *BLACK # or transparent
  # background: *SEMI_TRANSPARENT
  foreground: *WHITE
  font_size: "12px"
  border_width: 0
  vertical: "v"
  horizontal: "b"
  components_left:
    - type: "text"
      foreground: "#54546d"
      text: "  "
    - type: "text"
      text: "   0%"
      margin: "0px 10px 0px 0px"

    # - type: "memory"
    #   label: "<attr fs='12' fg='#54546d'>     </attr>{percent_usage}%"
    #   margin: "0px 10px 0px 0px"
    #   refresh_interval_ms: 1000

    - type: "cpu"
      label: "<attr fs = '13' fg='#FC4714'>   </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 3000

    - type: "gpu"
      label: "<attr fs='15' fg='#76B900'>󱝊  </attr>{percent_usage}%"
      margin: "0px 10px 0px 0px"
      refresh_interval_ms: 3000

    - type: "text"
      foreground: *COLOR_MAIN
      margin: "0px 10px 0px 0px"
      text: "󰝚"

    - type: "music"
      padding: "0 0"
      label_not_playing: ""
      label_paused: "󰐊 {song_title} - {artist_name} "
      label_playing: "{song_title} - {artist_name} "
      max_title_length: 35
      max_artist_length: 20
      # NOTE: the below <attr> tags are buggy when the song title has a "&" in it
      # label_paused: "<attr fg='#ef596f'> ▶</attr> {song_title} - {artist_name} "
      # label_playing: "<attr fg='#8AADF4'> 󰝚 </attr> {song_title} - {artist_name} "

  components_center:
    - type: "workspaces"
      border_width: 0
      border_radius: 0
      font_size: 14
      border_color: *COLOR_MAIN
      focused_workspace_background: "#21262d"
      focused_workspace_foreground: *WHITE
      displayed_workspace_background: "#21262d"
      default_workspace_background: "transparent"
      default_workspace_foreground: *WHITE

  components_right:
    # - type: "window title"
    #   padding: "0px 0px 0px 150px"

    - type: "tiling direction"
      font_size: "12px"
      label_horizontal: " "
      label_vertical: " "
      foreground: *WHITE
      padding: "0 10px"

    - type: "network"
      refresh_interval_ms: 3000
      foreground: "#2288DC"
      padding: "0 0px"
      font_family: "JetBrainsMono Nerd Font"
      # this doesn't seem to work
      label_wifi_strength_0: "󰤯 0%"
      label_wifi_strength_25: "󰤟 25%"
      label_wifi_strength_50: "󰤢 50%"
      label_wifi_strength_75: "󰤥 75%"
      label_wifi_strength_100: "󰤨 100%"
      label_no_internet: "<attr fg='#ef596f'></attr> "

    - type: "system tray"
      padding: "4px 5px"
      foreground: *COLOR_MAIN
      # label_expand_text:
      # label_collapse_text:

    - type: "volume"
      padding: "0 5px"
      # label: "<attr fs='15' fg='#fefefe'> </attr>{volume_level}%"
      label_mute: "<attr fs='15' fg='#ef596f'>󰸈  </attr>{volume_level}%"
      label_low: "<attr fs='15' fg='#fefefe'>󰖀 </attr>{volume_level}%"
      label_medium: "<attr fs='15' fg='#fefefe'>󰕾  </attr>{volume_level}%"
      label_high: "<attr fs='15' fg='#fefefe'>󰕾  </attr>{volume_level}%"

    - type: "battery"
      padding: "0 0px"
      label_draining: "<attr fs='12' fg='#fefefe'>󱊢</attr> {battery_level}%"
      label_power_saver: "<attr fs='12' fg='#89ca78'>󰌪 </attr> {battery_level}%"
      label_charging: "<attr fs='12' fg='#e5c07b'> </attr> {battery_level}%"

    - type: "clock"
      time_formatting: "ddd MMM d, hh:mm tt"
      padding: "0 5px"
      margin: "0 0 0 5px"

workspaces:
  - name: "term"
    keep_alive: false
    display_name: "  "
    # display_name: "     

  - name: "1"
    # display_name: "󰟒 "
    keep_alive: false

  - name: "2"
    keep_alive: false

  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

  - name: "spotify"
    display_name: "  "
    keep_alive: false

  - name: "mail"
    display_name: "󰇰 "
    keep_alive: false

  - name: "ticktick"
    display_name: "󰄴 "
    keep_alive: false

window_rules:
  # Window resizes
  - command: "resize borders -10px 0px 0px 0px"
    match_process_name: "msrdc"
  - command: "resize borders -2px -7px -15px -7px"
    match_process_name: "sioyek"
  - command: "resize borders +1px -7px -7px -8px"
    match_process_name: "neovide"
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam|vivaldi"
  - command: "resize borders -0px -9px -9px -9px"
    match_process_name: "TickTick"
  - command: "resize borders 0px 0px +3px +3px"
    match_process_name: "thorium"
  - command: "resize borders -0px -7px -7px -7px"
    match_process_name: "alacritty"
  - command: "resize borders +0px +2px +3px +2px"
    match_process_name: "Arduino IDE"
  - command: "resize borders -0px -7px -7px -7px"
    match_process_name: "sublime_text"
  - command: "resize borders +0px +3px +3px 0px"
    match_process_name: "firefox"
  - command: "resize borders +0px +2px -0px +2px"
    match_process_name: "mailspring"
  - command: "resize borders +1px +3px -2px +3px"
    match_process_name: "mercury"
  - command: "resize borders +1px +5px -2px +5px"
    match_process_name: "thorium"

  # Auto tile or float
  - command: "set tiling"
    match_process_name: "sioyek"

  - command: "set floating"
    match_title: "Go to"
  - command: "set floating"
    match_class_name: "#32770|SunAwtDialog"
  - command: "set floating"
    match_process_name: "Taskmgr"
  - command: "set floating"
    match_process_name: "WindowsTerminal|pwsh|OpenConsole"
  - command: "set floating"
    match_title: "This PC|Picture in picture"
  - command: "set floating"
    match_process_name: "localsend_app"
  - command: "set floating"
    match_process_name: "PowerToys.Peek.UI"
  - command: "set floating"
    match_class_name: "open"
  - command: "set floating"
    match_process_name: "Screen Snipping"
  - command: "set floating"
    match_class_name: "ApplicationFrameWindow|HwndWrapper*"
  - command: "set floating"
    match_process_name: "ProtonVPN"
  - command: "set floating"
    match_process_name: "ProtonVPNService"
  - command: "set floating"
    match_title: "Sync to Most Recent Page Read" # Kindle
  - command: "set floating"
    match_process_name: "ApplicationFrameHost"
    match_title: "Control Panel|Settings"
  - command: "set floating"
    match_process_name: "explorer"
  - command: "set floating"
    match_process_name: "Notepad"
  - command: "set floating"
    match_process_name: "sublime_text"
  - command: "set floating"
    match_process_name: "Photos"
  - command: "set floating"
    match_process_name: "Discord|Steam"
  - command: "set floating"
    match_process_name: "BCUninstaller"
  - command: "set floating"
    match_title: "Bitwarden"
  - command: "set floating"
    match_process_name: "PhoneExperienceHost"
  # the below doesn't work due to line 280 matching first and auto moving to
  # terminal workspace. works on config reload though.
  - command: "set floating"
    match_process_name: "alacritty"
    match_title: "/btop4win\\+\\+/"
    # - command: "set floating"
    #   match_process_name: "TickTick"

  # Ignore
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
  - command: "ignore"
    match_process_name: "TickTick"
  - command: "ignore"
    match_process_name: "Wintoys"
  - command: "ignore"
    match_process_name: "/ScreenClippingHost/"
  - command: "ignore"
    match_process_name: "Flow.Launcher"
  - command: "ignore"
    match_title: "WinUI Desktop" # PowerToys Peek
  - command: "ignore"
    match_title: "Run" # Win + R
  - command: "ignore"
    match_title: "Focus Timer" # TickTick
  - command: "ignore"
    match_process_name: "msrdc" # WSL gui windows
  # - command: "ignore"
  #   match_process_name: "EXCEL"
  - command: "ignore"
    match_process_name: "GHelper"
  - command: "ignore"
    match_process_name: "QuickLook"
  - command: "ignore"
    match_process_name: "ScreenColorPicker"
  - command: "ignore"
    match_process_name: "/LockApp/"

  # Auto send to workspace
  - command: "move to workspace term"
    match_title_name: "Alacritty"
    match_process_name: "alacritty"
  - command: "move to workspace spotify"
    match_process_name: "Spotify"
  - command: "move to workspace mail"
    match_process_name: "mailspring|thunderbird"
  - command: "move to workspace ticktick"
    match_process_name: "thorium"
    match_title: "TickTick - Today - TickTick" # only matches the TickTick PWA

keybindings:
  # Focus windows
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  # - command: "focus up"
  #   bindings: ["Alt+K"]
  # - command: "focus down"
  #   bindings: ["Alt+J"]

  # Window movement
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Window resize
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # General actions
  - command: "tiling direction toggle"
    binding: "Alt+Shift+D"
  - command: "toggle focus mode"
    binding: "Alt+F"
  - command: "toggle floating"
    binding: "Alt+Shift+F"
  - command: "toggle maximized"
    binding: "Alt+X"
  - command: "set minimized"
    binding: "Alt+C"
  # - command: "close"
  #   binding: "Alt+Q"
  - command: "exit wm"
    binding: "Alt+Shift+Z"
  - command: "reload config"
    binding: "Alt+Shift+R"
  # - command: "tiling direction vertical"
  #   binding: "Alt+V"

  # Open programs
  - command: "exec alacritty"
    binding: "Alt+Enter"
  - command: 'exec alacritty -o "shell=''pwsh''"' #alacritty in windows
    binding: "Alt+Shift+Enter"
  - command: 'exec alacritty -o "shell=''pwsh''" -e btop' #alacritty in windows
    binding: "Alt+B"
  - command: "exec thorium"
    binding: "Alt+W"

  # Focus specific workspaces
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"
  - command: "focus workspace ticktick"
    binding: "Alt+E"
  - command: "focus workspace mail"
    binding: "Alt+M"
  - command: "focus workspace term"
    binding: "Alt+Escape"
  - command: "focus workspace spotify"
    binding: "Alt+S"

  # Focus relative workspaces
  - command: "focus workspace recent"
    binding: "Alt+R"
  - command: "focus workspace next"
    binding: "Alt+D"
  - command: "focus workspace prev"
    binding: "Alt+A"

  # Move to workspace
  - commands: ["move to workspace term"]
    binding: "Alt+Shift+Escape"
  - commands: ["move to workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9"]
    binding: "Alt+Shift+9"
  - commands: ["move to workspace ticktick"]
    binding: "Alt+Shift+E"
  - commands: ["move to workspace mail"]
    binding: "Alt+Shift+M"
  - commands: ["move to workspace spotify"]
    binding: "Alt+Shift+S"
